version: '3'

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    build: ./mysql
    # image: mysql:latest
    env_file:
      - .env.mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default



volumes:
  jenkins_home:
  mysql_data:

networks:
  infra_default:
    driver: bridge
